apiVersion: v1
kind: Service
metadata:
  name: {{ include "worker.fullname" .}}
  namespace: cuegrowth
  labels:
    app: worker
spec:
  selector:
    {{- include "worker.selectorLabels" . | nindent 4}}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
