apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  namespace: cuegrowth
spec:
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
